/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-dim": "#111318",
        "secondary": "#adc6ff",
        "primary-fixed-dim": "#ddb7ff",
        "on-error": "#690005",
        "on-background": "#e2e2e8",
        "primary-container": "#b76dff",
        "on-secondary": "#002e6a",
        "error": "#ffb4ab",
        "outline-variant": "#4d4354",
        "surface-tint": "#ddb7ff",
        "tertiary-container": "#009eb9",
        "on-primary": "#490080",
        "on-primary-fixed": "#2c0051",
        "surface-variant": "#333539",
        "tertiary-fixed-dim": "#4cd7f6",
        "inverse-on-surface": "#2f3035",
        "surface-container": "#1e2024",
        "surface-container-high": "#282a2e",
        "secondary-container": "#0566d9",
        "on-secondary-fixed-variant": "#004395",
        "surface-container-highest": "#333539",
        "tertiary-fixed": "#acedff",
        "error-container": "#93000a",
        "tertiary": "#4cd7f6",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#6900b3",
        "on-tertiary": "#003640",
        "background": "#111318",
        "on-secondary-container": "#e6ecff",
        "inverse-surface": "#e2e2e8",
        "secondary-fixed": "#d8e2ff",
        "on-primary-container": "#400071",
        "outline": "#988d9f",
        "primary": "#ddb7ff",
        "on-secondary-fixed": "#001a42",
        "surface": "#111318",
        "on-tertiary-fixed": "#001f26",
        "primary-fixed": "#f0dbff",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-surface-variant": "#cfc2d6",
        "secondary-fixed-dim": "#adc6ff",
        "inverse-primary": "#842bd2",
        "surface-container-lowest": "#0c0e12",
        "surface-bright": "#37393e",
        "on-surface": "#e2e2e8",
        "surface-container-low": "#1a1c20",
        "on-tertiary-container": "#002f38"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "gutter": "24px",
        "unit": "8px",
        "margin-mobile": "16px",
        "container-max": "1280px"
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "display-xl": ["Outfit", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "sans": ["Plus Jakarta Sans", "sans-serif"],
        "heading": ["Outfit", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
